Jdp230801 15
piotr-grosicki/project-jdp-2308-01 pull request #7
Opened 2023-08-01 20:32 UTC by DanielKryszkiewicz

2023-08-01 22:02 UTC, Barhwald requested changes
Brakuje określenia relacji między encją Customer a encją Cart.

(name = "Customers") powinno się znaleźć przy adnotacji @Entity, nie @Table

2023-08-02 23:11 UTC, ercoire requested changes

2023-08-02 23:11 UTC, ercoire commented on src/main/java/com/kodilla/ecommercee/domain/Customer.java
> +  //  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
zamiast "user" mamy "customers" według schematu

2023-08-02 23:11 UTC, ercoire commented on src/main/java/com/kodilla/ecommercee/domain/Customer.java
> +    @Column(nullable = false)
tego pola nie ma w schemacie

2023-08-07 13:17 UTC, ercoire approved these changes

2023-08-07 20:10 UTC, Barhwald approved these changes

2023-08-12 21:05 UTC, merged