JDP230801-13
piotr-grosicki/project-jdp-2308-01 pull request #8
Opened 2023-08-01 22:24 UTC by Barhwald

Group entity created

2023-08-03 20:32 UTC, ercoire requested changes

2023-08-03 20:32 UTC, ercoire commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +//            mappedBy = "group",
mappedBy wskazuje kolumnę po stronie "many" czyli to będzie "product"

2023-08-03 20:32 UTC, ercoire commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    private long id;
może lepiej będzie użyć wrappera, czyli Long?

2023-08-07 21:00 UTC, Barhwald commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +//            mappedBy = "group",
mappedBy, jak podaje Kodilla "określa pole encji z prawej strony relacji 1 : N (1 grupa : wiele produktów), które przechowuje referencję do obiektu encji znajdującej się po lewej stronie relacji 1 : N". Czyli jest klasa Product zawierająca pole private Group group.

2023-08-08 21:26 UTC, ercoire approved these changes

2023-08-12 20:50 UTC, merged